---
image: docker:///cloudfoundry/inigo-ci

params:
  GOROOT: /usr/local/go
  GINKGO_PARALLEL: true

run:
  path: bash
  args:
    - '-c'
    - |
      cd inigo/ &&
      ./src/github.com/cloudfoundry-incubator/inigo/scripts/dev-test-inner "$@"
