---
image: docker:///cloudfoundry/inigo-ci

params:
  GINKGO_PARALLEL: "GINKGO_PARALLEL_PLACEHOLDER"
  DEFAULT_EVENTUALLY_TIMEOUT:
  INIGO_REPEAT_COUNT: 1
  USE_TMPFS: true

run:
  path: bash
  args:
    - '-c'
    - |
      cd inigo/ &&
      ./src/github.com/cloudfoundry-incubator/inigo/scripts/dev-test-inner "$@"
